<?php

namespace Editxt\ContentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentRelatedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRelatedRepository extends EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function getRelatedByItem($id)
    {
        $queryBuiler = $this->createQueryBuilder('rel')
            ->select('rel, c, i')
            ->join('rel.item', 'i')
            ->join('rel.content', 'c')
            ->where('rel.item = :item_id')
            ->setParameter('item_id', $id);

        $query = $queryBuiler->getQuery();
        return $query->getResult();
    }

}
