<?php

namespace Editxt\ContentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function getListQueryBuilder()
    {
        $queryBuiler = $this->createQueryBuilder('cnt')
            ->select('cnt')
            ->orderBy('cnt.id', 'desc');

        return $queryBuiler;
    }
}
