<?php

namespace Editxt\ContentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubTitleRepository extends EntityRepository
{

    /**
     * @return QueryBuilder
     */
    public function findNameOrNullResult($name)
    {
        $queryBuiler = $this->createQueryBuilder('s')
            ->select('s')
            ->where("s.name = :name")
            ->setParameter('name', $name);

        return $queryBuiler->getQuery()->getOneOrNullResult();
    }

}
