<?php

namespace Editxt\ContentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{

    /**
     * @return QueryBuilder
     */
    public function getTagsByNames($names)
    {

        $queryBuiler = $this->createQueryBuilder('t')
            ->select('t')
            ->where("t.name IN (:namesArray)")
            ->setParameter('namesArray', $names);

        return $queryBuiler->getQuery()->execute();
    }

    /**
     * @return QueryBuilder
     */
    public function findNameOrNullResult($name)
    {
        $queryBuiler = $this->createQueryBuilder('t')
            ->select('t')
            ->where("t.name = :name")
            ->setParameter('name', $name);

        return $queryBuiler->getQuery()->getOneOrNullResult();
    }

}
